# Generated by Django 5.0.6 on 2024-12-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_person_month_person_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date',
        ),
        migrations.AddField(
            model_name='person',
            name='deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
